<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class ParentsCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        if (Auth::guest())
        {
            return true;
        }
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'       =>'required',
            'profession' =>'required',
            'address'    =>'required',
            'phone'      =>'required',
            'email'      =>'required|email',
            'password'   =>'required'
        ];
    }
    public function messages()
    {
        return [
            'name.required'      =>'Parent Name is required',
            'profession.required'=>'Parent Profession is required',
            'address.required'   =>'Parent Address is required',
            'phone.required'   =>'Mobile Number is required',
            'email'              =>'Parent Email is required',
            '$password'          =>'Parent Account Password is required',
        ]; // TODO: Change the autogenerated stub
    }
}
