<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class TeacherRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'first_name'       =>'required',
            'last_name' =>'required',
            'address'    =>'required',
            'phone'      =>'required',
            'photo_id'  =>'required',
            'email'      =>'required|email',
            'password'   =>'required'
        ];
    }
    public function messages()
    {
        return [
            'first_name.required'      =>'Teacher First Name is required',
            'last_name.required'=>'Teacher Last Name is required',
            'address.required'   =>'Teacher Address is required',
            'phone.required'   =>'Mobile Number is required',
            'email'              =>'Teacher Email is required',
            '$password'          =>'Teacher Account Password is required',
        ]; // TODO: Change the autogenerated stub
    }

}
